fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    apache:
      repo: 'https://github.com/puppetlabs/puppetlabs-apache.git'
      ref: '1.1.1'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.1.1'
    gcc:
      repo: 'https://github.com/puppetlabs/puppetlabs-gcc.git'
      ref: '0.2.0'
    passenger:
      repo: 'https://github.com/eshamow/puppetlabs-passenger.git'
      ref: '09d181a2a818b177db106917c87327a0d8593dbb'
    ruby:
      repo: 'https://github.com/puppetlabs/puppetlabs-ruby.git'
      ref: '734a33bb7f7670136e77179aafeeebb81d8d14d3'
  symlinks:
    profile_passenger: "#{source_dir}"
