HOSTS:
  centos-65-x8664:
    roles:
      - master
    platform: centos-65-x86_64
    box: opscode_centos-6.5_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  centos-65-i386:
    roles:
      - master
    platform: centos-65-i386
    box: opscode_centos-6.5-i386_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  centos-70-x8664:
    roles:
      - master
    platform: centos-70-x86_64
    box: opscode_centos-7.0_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  centos-70-i386:
    roles:
      - master
    platform: centos-70-i386
    box: opscode_centos-7.0-i386_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  debian-6010-x8664:
    roles:
      - master
    platform: debian-6010-x86_64
    box: opscode_debian-6.0.10_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  debian-6010-i386:
    roles:
      - master
    platform: debian-6010-i386
    box: opscode_debian-6.0.10-i386_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  debian-76-x8664:
    roles:
      - master
    platform: debian-76-x86_64
    box: opscode_debian-7.6_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  debian-76-i386:
    roles:
      - master
    platform: debian-76-i386
    box: opscode_debian-7.6-i386_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  ubuntu-1004-x8664:
    roles:
      - master
    platform: ubuntu-1004-x86_64
    box: opscode_ubuntu-10.04_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  ubuntu-1004-i386:
    roles:
      - master
    platform: ubuntu-1004-i386
    box: opscode_ubuntu-10.04-i386_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  ubuntu-1204-x8664:
    roles:
      - master
    platform: ubuntu-1204-x86_64
    box: opscode_ubuntu-12.04_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  ubuntu-1204-i386:
    roles:
      - master
    platform: ubuntu-1204-i386
    box: opscode_ubuntu-12.04-i386_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  ubuntu-1404-x8664:
    roles:
      - master
    platform: ubuntu-1404-x86_64
    box: opscode_ubuntu-14.04_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-14042-x64-vbox4210-nocm.box
    hypervisor: vagrant
  ubuntu-1404-i386:
    roles:
      - master
    platform: ubuntu-1404-i386
    box: opscode_ubuntu-14.04-i386_chef-provisionerless
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-14042-x64-vbox4210-nocm.box
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type: foss
